[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]
packageManager = "pnpm"

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmds = ["pnpm run start"]

[variables]
NIXPACKS_PATH = "/app"
