[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmds = ["npm run start"]

[variables]
NIXPACKS_PATH = "/app"
